# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1

jobs:
  print_hello:
    docker:
      - image: circleci/alpine
    steps:
      - run: echo "hello"

  print_world:
    docker:
      - image: circleci/alpine
    steps:
      - run: echo "world"
      
  print_env_var:
    docker:
      - image: circleci/alpine
    steps:
      - run: echo $TEST_VARIABLE

  print_hello_world_to_file:
    docker:
      - image: circleci/alpine
    steps:
      - run: echo "Hello from the first job" >> output.txt
      - persist_to_workspace:
          root: /tmp/demo_project
          paths:
            - output.txt

  read_hello_world_from_file:
    docker:
      - image: circleci/alpine
    steps:
      - run: cat output.txt
      - attach_workspace:
          at: /tmp/demo_project

# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - print_hello_world_to_file
      - read_hello_world_from_file:
          requires:
            - print_hello_world_to_file


